//-------------------------------------------------
// Gnrl
//---------------------------------------------------
$SRV_HOME/rtl/gnrl/arithmetic/srv_booth.vp
$SRV_HOME/rtl/gnrl/arithmetic/srv_compressor32.vp
$SRV_HOME/rtl/gnrl/arithmetic/srv_compressor42.vp
$SRV_HOME/rtl/gnrl/arithmetic/srv_divider32.vp
$SRV_HOME/rtl/gnrl/arithmetic/srv_multiplier32.vp
$SRV_HOME/rtl/gnrl/logic/srv_oh2bin.vp
$SRV_HOME/rtl/gnrl/logic/srv_onehot_demux.vp
$SRV_HOME/rtl/gnrl/logic/srv_onehot_mux.vp
$SRV_HOME/rtl/gnrl/logic/srv_plrs.vp
$SRV_HOME/rtl/gnrl/logic/srv_sync_fifo.vp
$SRV_HOME/rtl/gnrl/logic/srv_tiny_arb.vp
$SRV_HOME/rtl/gnrl/memory/srv_tpram.vp
$SRV_HOME/rtl/gnrl/memory/srv_spram.vp
//-------------------------------------------------
// Bus
//---------------------------------------------------
$SRV_HOME/rtl/bus/srv_addr_hit_v1.v
$SRV_HOME/rtl/bus/srv_addr_hit_v2.v
$SRV_HOME/rtl/bus/srv_icb_dslv.v
$SRV_HOME/rtl/bus/srv_icb_1vN.v
$SRV_HOME/rtl/bus/srv_icb_Nv1.v
$SRV_HOME/rtl/bus/srv_icb_NvN.v
$SRV_HOME/rtl/bus/srv_icb_mem.v
//-------------------------------------------------
// Cache
//---------------------------------------------------
$SRV_HOME/rtl/cache/srv_icache_data_mem.vp
$SRV_HOME/rtl/cache/srv_icache_tag_mem.vp
$SRV_HOME/rtl/cache/srv_icache_bridge.vp
$SRV_HOME/rtl/cache/srv_icache_kernal.vp
$SRV_HOME/rtl/cache/srv_icache.vp
$SRV_HOME/rtl/cache/srv_dcache.vp
//-------------------------------------------------
// Import
//---------------------------------------------------
$SRV_HOME/rtl/import/XS-Verilog-Library-DIV/compressor_3_2.sv
$SRV_HOME/rtl/import/XS-Verilog-Library-DIV/int_div_radix_16_v4.sv
$SRV_HOME/rtl/import/XS-Verilog-Library-DIV/lzc.sv
$SRV_HOME/rtl/import/XS-Verilog-Library-DIV/r16_block.sv
$SRV_HOME/rtl/import/XS-Verilog-Library-DIV/radix_4_sign_coder.sv
$SRV_HOME/rtl/import/XS-Verilog-Library-DIV/radix_4_sign_detector.sv
//-------------------------------------------------
// Core Package
//---------------------------------------------------
$SRV_HOME/rtl/core/package/srv_constant.v
$SRV_HOME/rtl/core/package/srv_parameter.v
//-------------------------------------------------
// Core
//---------------------------------------------------
$SRV_HOME/rtl/core/frontend/srv_bpu_ctrl.vp
$SRV_HOME/rtl/core/frontend/srv_bpu_btb.vp
$SRV_HOME/rtl/core/frontend/srv_bpu_bht.vp
$SRV_HOME/rtl/core/frontend/srv_bpu_pht.vp
$SRV_HOME/rtl/core/frontend/srv_bpu.vp
$SRV_HOME/rtl/core/frontend/srv_ifu_matrix.vp
$SRV_HOME/rtl/core/frontend/srv_ifu_split.vp
$SRV_HOME/rtl/core/frontend/srv_ifu_predec.vp
$SRV_HOME/rtl/core/frontend/srv_ifu_pipe.vp
$SRV_HOME/rtl/core/frontend/srv_ifu.vp
$SRV_HOME/rtl/core/frontend/srv_idu_decode.vp
$SRV_HOME/rtl/core/frontend/srv_idu_translate.vp
$SRV_HOME/rtl/core/frontend/srv_idu_merge.vp
$SRV_HOME/rtl/core/frontend/srv_idu_pipe.vp
$SRV_HOME/rtl/core/frontend/srv_idu.vp
$SRV_HOME/rtl/core/backend/srv_rr_remap.vp
$SRV_HOME/rtl/core/backend/srv_rr_ctrl2.vp
$SRV_HOME/rtl/core/backend/srv_rr_ctrl.vp
$SRV_HOME/rtl/core/backend/srv_rr_rat.vp
$SRV_HOME/rtl/core/backend/srv_rr_pipe.vp
$SRV_HOME/rtl/core/backend/srv_rr.vp
$SRV_HOME/rtl/core/backend/srv_disp_split.vp
$SRV_HOME/rtl/core/backend/srv_disp_lsu.vp
$SRV_HOME/rtl/core/backend/srv_disp_bu.vp
$SRV_HOME/rtl/core/backend/srv_disp_iu.vp
$SRV_HOME/rtl/core/backend/srv_disp.vp
$SRV_HOME/rtl/core/backend/srv_issue_iu.vp
$SRV_HOME/rtl/core/backend/srv_issue_bu.vp
$SRV_HOME/rtl/core/backend/srv_issue.vp
$SRV_HOME/rtl/core/backend/srv_fu_alu_kernal.vp
$SRV_HOME/rtl/core/backend/srv_fu_alu.vp
$SRV_HOME/rtl/core/backend/srv_fu_mul.vp
$SRV_HOME/rtl/core/backend/srv_fu_div.vp
$SRV_HOME/rtl/core/backend/srv_fu_bu.vp
$SRV_HOME/rtl/core/backend/srv_fu.vp
$SRV_HOME/rtl/core/backend/srv_rob_entry.vp
$SRV_HOME/rtl/core/backend/srv_rob.vp
$SRV_HOME/rtl/core/backend/srv_csr.vp
$SRV_HOME/rtl/core/backend/srv_prf.vp
$SRV_HOME/rtl/core/backend/srv_rtu_redir_pc.vp
$SRV_HOME/rtl/core/backend/srv_rtu.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_iq_split.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_iq_merge.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_iq_ld.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_iq_st.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_iq.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_ag.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_lsu_buffer.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_lsu_in.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_lsu_matrix.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_lsu_resp.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_lsu_rpack.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_lsu_stio_req.vp
$SRV_HOME/rtl/core/memblk/srv_mblk_lsu.vp
$SRV_HOME/rtl/core/sideband/srv_flush_ctrl.vp
$SRV_HOME/rtl/core/sideband/srv_biu.vp
//-------------------------------------------------
// TOP
//---------------------------------------------------
$SRV_HOME/rtl/top/srv_frontend.v
$SRV_HOME/rtl/top/srv_backend.v
$SRV_HOME/rtl/top/srv_memblk.v
$SRV_HOME/rtl/top/srv_core.v
$SRV_HOME/rtl/top/srv_top.v
